services:
  thehouse-back:
    image: thehouse-back:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped

  thehouse-front:
    build: .
    image: thehouse-front:latest
    ports:
      - "3002:80"
    restart: unless-stopped